
# spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.fucybzqprgjuxwghwfrv&password=010203!Daniel!070809

# spring.datasource.username=postgres.fucybzqprgjuxwghwfrv
# spring.datasource.password=010203!Daniel!070809

# ./mvnw spring-boot:run
# http://localhost:8080/api/users

spring.application.name=backend

# 1. URL з user і password параметрами (екрановані спеціальні символи)
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.hltwgrchywhmcfpvtqvl&password=N7%23vQ2%21zL9%40kR4%24mX8%26cT1%5EpW5*Hj&sslmode=require

# 2. Альтернативно - username і password окремо (закоментуємо поки)
# spring.datasource.username=postgres.hltwgrchywhmcfpvtqvl 
# spring.datasource.password=N7#vQ2!zL9@kR4$mX8&cT1^pW5*Hj

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=3

# Секретний ключ для JWT (це просто випадковий 256-бітний рядок у Base64). 
# У реальному житті він має бути у змінних середовища!
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Час життя токена ( 30 хвилин * 60 секунд * 1000 мілісекунд = 1800000 )
jwt.expiration=1800000

# --- НОВІ НАЛАШТУВАННЯ GMAIL ДЛЯ ОБХОДУ RENDER ---
spring.mail.host=smtp.gmail.com
# Змінюємо порт з 587 на 465 (SSL)
spring.mail.port=465
spring.mail.username=roomies.app@gmail.com
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
# Вимикаємо STARTTLS, бо ми використовуємо чистий SSL
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

# Вмикаємо примусовий SSL для порту 465
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false

# Збільшуємо час очікування, бо Render може "думати" довше
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

# Якщо використовуєш Spring Boot 3.x (Hibernate 6)
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Якщо не спрацює, спробуй цей (для старих версій Hibernate):
# spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisDialect

# І ОБОВ'ЯЗКОВО додай це, щоб Hibernate коректно створював/оновлював типи
spring.jpa.properties.hibernate.dialect.spatial=true

# Supabase Storage
supabase.url=https://hltwgrchywhmcfpvtqvl.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsdHdncmNoeXdobWNmcHZ0cXZsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzQwMTk4NCwiZXhwIjoyMDg4OTc3OTg0fQ.YIzJiUKyjuPXrhedbyW74dNCgUHKfRd5W0nfvlmfOdE
supabase.bucket.avatars=avatars
