spring.application.name=backend

# НОВИЙ URL (з Connection Pooler). Обов'язково встав своє нове посилання:
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.fucybzqprgjuxwghwfrv&password=010203!Daniel!070809

spring.datasource.username=postgres.fucybzqprgjuxwghwfrv
spring.datasource.password=010203!Daniel!070809

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true