
# spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.fucybzqprgjuxwghwfrv&password=010203!Daniel!070809

# spring.datasource.username=postgres.fucybzqprgjuxwghwfrv
# spring.datasource.password=010203!Daniel!070809

# ./mvnw spring-boot:run
# http://localhost:8080/api/users

spring.application.name=backend

# 1. URL з user і password параметрами (екрановані спеціальні символи)
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.hltwgrchywhmcfpvtqvl&password=N7%23vQ2%21zL9%40kR4%24mX8%26cT1%5EpW5*Hj&sslmode=require

# 2. Альтернативно - username і password окремо (закоментуємо поки)
# spring.datasource.username=postgres.hltwgrchywhmcfpvtqvl 
# spring.datasource.password=N7#vQ2!zL9@kR4$mX8&cT1^pW5*Hj

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=3

# Секретний ключ для JWT (це просто випадковий 256-бітний рядок у Base64). 
# У реальному житті він має бути у змінних середовища!
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Час життя токена ( 30 хвилин * 60 секунд * 1000 мілісекунд = 1800000 )
jwt.expiration=1800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=danieldragomanov@gmail.com
spring.mail.password=ghgafvvlxnifwcjk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true