### ==========================================
### ТЕСТУВАННЯ ПРОФІЛЮ КОРИСТУВАЧА (USER API)
### Увага: Усі запити тепер йдуть через /me (для поточного авторизованого користувача)
### ==========================================

### 1. Отримати дані про себе (GET /me)
GET http://localhost:8080/api/users/me
Authorization: Bearer {{auth_token}}

### 2. Оновити свій профіль (PUT /me)
PUT http://localhost:8080/api/users/me
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "email": "mike_test@mail.com",
  "firstName": "ОновленеІм'я",
  "lastName": "ОновленеПрізвище",
  "birthDate": "2000-08-22",
  "gender": "male",
  "phoneNumber": "+380679876543",
  "bio": "Студент. Багато вчуся, тому дуже ціную тишу.",
  "occupation": "student",
  "avatarUrl": "https://example.com/my-new-avatar.png"
}

### 3. Частково оновити свої налаштування та звички (PATCH /me/preferences)
# Ці дані автоматично запакуються в JSONB колонку lifestyle_flags у базі даних
PATCH http://localhost:8080/api/users/me/preferences
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "sleep_schedule": "early_bird",
  "guests_frequency": "rarely",
  "noise_tolerance": "low",
  "cleanliness_level": "high",
  "dietary_preferences": "none",
  "isSmoker": false,
  "drinksAlcohol": false,
  "partyHabits": false
}


### ==========================================
### ТЕСТУВАННЯ АЛГОРИТМУ МЕТЧИНГУ (MATCHING API)
### ==========================================

### 4. Отримати список сумісних сусідів (Дефолтний ліміт 20)
# УВАГА:
# Заміни "2" у параметрі cityId на ID міста, де шукаємо (наприклад, Львів).
GET http://localhost:8080/api/users/me/potential-matches?cityId=4
Authorization: Bearer {{auth_token}}

### 5. Отримати список із жорсткою пагінацією (тільки топ-2 найкращих кандидати)
# Додаємо параметри size=2 та page=0
GET http://localhost:8080/api/users/me/potential-matches?cityId=2&size=2&page=0
Authorization: Bearer {{auth_token}}