### 1. Створити новий розклад для користувача (PUT)
PUT http://localhost:8080/api/users/b6f277af-5c05-4a19-aebc-ef7e12aa7be2/work-schedule
Content-Type: application/json

{
  "scheduleType": "Гібридний",
  "baseLocation": "Офіс у Львові",
  "evenPeriodLocation": "Робота з дому",
  "oddPeriodLocation": "Робота з офісу",
  "week1OfficeDays": [1, 3, 5],
  "week2OfficeDays": [2, 4],
  "shiftWorkDays": 5,
  "shiftRestDays": 2
}


### 2. Отримати розклад користувача (GET)
GET http://localhost:8080/api/users/b6f277af-5c05-4a19-aebc-ef7e12aa7be2/work-schedule


### 3. Оновити розклад (той самий PUT запит, але з новими даними)
PUT http://localhost:8080/api/users/b6f277af-5c05-4a19-aebc-ef7e12aa7be2/work-schedule
Content-Type: application/json

{
  "scheduleType": "Віддалена",
  "baseLocation": "Дім",
  "evenPeriodLocation": "Дім",
  "oddPeriodLocation": "Дім",
  "week1OfficeDays": [],
  "week2OfficeDays": [],
  "shiftWorkDays": 0,
  "shiftRestDays": 0
}


### 4. Видалити розклад (DELETE)
DELETE http://localhost:8080/api/users/b6f277af-5c05-4a19-aebc-ef7e12aa7be2/work-schedule